### ISSUE TITLE
support __repr__ method

### ISSUE THREAD

**Issue by saroad2** [FebruaryBreeze/json-schema-to-class#11]
Hello!

This is a very helpful tool. Thank you for it!

One thing I'm missing is a `__repr__` method in the generated classes.
Once you approve this feature request, I'll go ahead and implement it.

**Comment by SF-Zhou** [comment]
This feature is approved and appriciated. 😉

**Comment by saroad2** [comment]
This issue has been solved in #12, therefore closing it.
